# What is Scikit-learn?
*Scikit-learn* has emerged as a powerful and user-friendly Python library. Its simplicity and versatility make it a better choice for both beginners and seasoned data scientists to build and implement machine learning models. In this article, we will explore about Sklearn.
*Scikit-learn* is an open-source Python library that implements a range of machine learning, pre-processing, cross-validation, and visualization algorithms using a unified interface. It is an open-source machine-learning library that provides a plethora of tools for various machine-learning tasks such as Classification, Regression, Clustering, and many more.

# Installation of Scikit- learn
```
!pip install -U scikit-learn
```
<!-- The latest version of Scikit-learn is 1.5 and it requires Python 3.8 or newer. -->
Scikit-learn requires:  
* NumPy
* SciPy as its dependencies.

### Step 1: Load a Dataset
Loading exemplar dataset: scikit-learn comes loaded with a few example datasets like the iris and digits datasets for classification and the boston house prices dataset for regression. 

In [18]:
# load the iris dataset as an example 
from sklearn.datasets import load_iris 
iris = load_iris() 

# store the feature matrix (X) and response vector (y)  ----  load_iris func return Bunch() data=data, target=target, frame=frame,...)
X = iris.data 
y = iris.target 

# store the feature and target names 
feature_names = iris.feature_names 
target_names = iris.target_names 

# printing features and target names of our dataset 
print("Feature names:", feature_names) 
print("Target names:", target_names) 

# X and y are numpy arrays 
print("\nType of X is:", type(X)) 

# printing first 5 input rows 
print("\nFirst 5 rows of X:\n", X[:5])

# print(type(iris))
print(iris.target[[10, 25, 50]])
print(type(iris.target[[10, 25, 50]])) # array([0, 0, 1])
print(list(iris.target_names))

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

Type of X is: <class 'numpy.ndarray'>

First 5 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
<class 'sklearn.utils._bunch.Bunch'>
[0 0 1]
<class 'numpy.ndarray'>
['setosa', 'versicolor', 'virginica']
